---
# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/latest/configuration/ and in linters documentation

APPLY_FIXES: none # all, none, or list of linter keys
# ENABLE: # If you use ENABLE variable, all other languages/formats/tooling-formats will be disabled by default
# ENABLE_LINTERS: # If you use ENABLE_LINTERS variable, all other linters will be disabled by default
DISABLE_LINTERS:
  - PYTHON_FLAKE8
  - PYTHON_ISORT

SHOW_ELAPSED_TIME: true
PYTHON_MYPY_DISABLE_ERRORS: true
PYTHON_PYRIGHT_DISABLE_ERRORS: true
PYTHON_PYLINT_DISABLE_ERRORS: true
