---
# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/latest/configuration/ and in linters documentation

APPLY_FIXES: none # all, none, or list of linter keys
SHOW_ELAPSED_TIME: true
# DISABLE_ERRORS: true # Uncomment if you want MegaLinter to detect errors but not block CI to pass
