---
name: "Guru to GitHub"
description: "Sync content from Guru to GitHub"
branding:
  icon: "copy"
  color: "green"
inputs:
  guru_collection_id:
    description: "ID of the Guru Collection to sync"
    required: true
  collection_directory_path:
    description: "Path to the directory where the Collection and metadata file should be synced to"
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        lfs: true
    - name: git config user
      shell: bash
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
    - name: Install pipenv
      shell: bash
      run: pip install --user pipenv
    - uses: actions/setup-python@v4
      with:
        python-version-file: "${{ github.action_path }}/.python-version"
    - name: Install dependencies
      shell: bash
      run: pipenv install
      env:
        PIPENV_PIPFILE: ${{ github.action_path }}/Pipfile
    # Create the collection directory so we can use it as the working directory
    # This allows us to keep the metadata file in the same directory as the collection(s)
    - name: Create the collection directory if it does not exist
      shell: bash
      run: mkdir -p  ${{ inputs.collection_directory_path }}
    - name: Sync collection
      working-directory: ${{ inputs.collection_directory_path }}
      shell: bash
      run: pipenv run python ${{ github.action_path }}/github_publisher.py
      env:
        PIPENV_PIPFILE: ${{ github.action_path }}/Pipfile
        GURU_COLLECTION_ID: ${{ inputs.guru_collection_id }}
        COLLECTION_DIRECTORY_PATH: ${{ inputs.collection_directory_path }}
    - name: Pull changes from sync so we can update the metadata file
      if: ${{ !env.DRY_RUN }}
      shell: bash
      run: git add -A && git pull --autostash
    - uses: stefanzweifel/git-auto-commit-action@8756aa072ef5b4a080af5dc8fef36c5d586e521d # v5.0.0
      if: ${{ !env.DRY_RUN }}
      with:
        file_pattern: "${{ inputs.collection_directory_path }}/**/resources/*"
        commit_message: "Update resources"
        commit_author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
    - uses: stefanzweifel/git-auto-commit-action@8756aa072ef5b4a080af5dc8fef36c5d586e521d # v5.0.0
      if: ${{ !env.DRY_RUN }}
      with:
        file_pattern: "${{ inputs.collection_directory_path }}/GitHubPublisher.json"
        commit_message: "Update GitHubPublisher.json"
        commit_author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
