---
name: "Guru to GitHub"
description: "Sync content from Guru to GitHub"
branding:
  icon: "copy"
  color: "green"
inputs:
  guru_collection_id:
    description: "ID of the Guru collection to sync"
    required: true
  working_directory_path:
    description: "Path to the directory where the collection and metadata file should be synced to"
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        lfs: true
    - name: git config user
      shell: bash
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
    - name: Install pipenv
      shell: bash
      run: pip install --user pipenv
    - uses: actions/setup-python@v4
      with:
        python-version-file: "${{ github.action_path }}/.python-version"
    - name: Install dependencies
      shell: bash
      run: pipenv install
      env:
        PIPENV_PIPFILE: ${{ github.action_path }}/Pipfile
    - name: Create the working directory if it doesn't exist
      shell: bash
      run: mkdir -p  ${{ inputs.working_directory_path }}
    - name: Sync collection
      working-directory: ${{ inputs.working_directory_path }}
      shell: bash
      run: pipenv run python ${{ github.action_path }}/github_publisher.py
      env:
        PIPENV_PIPFILE: ${{ github.action_path }}/Pipfile
        GURU_COLLECTION_ID: ${{ inputs.guru_collection_id }}
    - name: Pull changes from sync so we can update the metadata file
      shell: bash
      run: git pull
    - name: Verify changed files
      uses: tj-actions/verify-changed-files@54e20d3c522fbeed99ebaf2e38a1eb33214c58ba # v16.1.1
      id: verify-changed-files
    - name: List all changed files tracked and untracked files
      run: |
        echo "Changed files: ${{ steps.verify-changed-files.outputs.changed_files }}"
      shell: bash
    - uses: stefanzweifel/git-auto-commit-action@8756aa072ef5b4a080af5dc8fef36c5d586e521d # v5.0.0
      with:
        file_pattern: ".gitattributes ${{ inputs.working_directory_path }}/**/resources/*"
        commit_message: "Update resources"
        commit_author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
    - uses: stefanzweifel/git-auto-commit-action@3ea6ae190baf489ba007f7c92608f33ce20ef04a # v4.16.0
      with:
        file_pattern: "${{ inputs.working_directory_path }}/GitHubPublisher.json"
        commit_message: "Update GitHubPublisher.json"
        commit_author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
