#############################  Cache  ###############################

# Enable link caching to avoid checking the same links on multiple runs.
cache = true

#############################  Requests  ############################

# When links are available using HTTPS, treat HTTP links as errors.
require_https = true

#############################  Exclusions  ##########################

# Exclude version comparison link.
exclude = ['https:\/\/github\.com\/.+\/.+\/compare\/v.+\.\.\.v.+']
