---
name: Release

on:
  push:
    branches: [main]

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    uses: parkerbxyz/.github/.github/workflows/release.yml@main
    with:
      release-type: "python"
